version: '3.3'

services:

  drupal:
    image: drupal
    ports:
      - 8080:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/sites
    
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites: